DATA_ARRAY = [
    {
        "id": 1,
        "name": "Jane Elizabeth Kempton",
        "madienName": "Twitchell",
        "voiceType": "contralto",
        "yearsActiveStart": "1850",
        "yearsActiveEnd": "1921",
        "dateOfDeath": "1922-03-13",
        "url": "https://en.wikipedia.org/wiki/Jenny_Twitchell_Kempton",
    },
    {
        "id": 2,
        "name": "Clara Louise Kellogg",
        "maidenName": None,
        "voiceType": "soprano",
        "yearsActiveStart": "1861",
        "yearsActiveEnd": "1886",
        "dateOfDeath": "1916-05-13",
        "url": "https://en.wikipedia.org/wiki/Clara_Louise_Kellogg",
    },
    {
        "id": 3,
        "name": 'Amalia "Minnie" Mignon Hauck',
        "maidenName": None,
        "voiceType": "mezzo-soprano",
        "yearsActiveStart": "1866",
        "yearsActiveEnd": None,
        "dateOfDeath": "1929-02-06",
        "url": "https://en.wikipedia.org/wiki/Minnie_Hauk",
    },
    {
        "id": 4,
        "name": "Annie Louise Cary",
        "maidenName": None,
        "voiceType": "contralto",
        "yearsActiveStart": "1868",
        "yearsActiveEnd": "1882",
        "dateOfDeath": "1921-04-03",
        "url": "https://en.wikipedia.org/wiki/Annie_Louise_Cary",
    },
    {
        "id": 5,
        "name": "Julie Rosewald",
        "maidenName": "Eichberg",
        "voiceType": "soprano",
        "yearsActiveStart": "1875",
        "yearsActiveEnd": "1902",
        "dateOfDeath": "1906-07-16",
        "url": "https://en.wikipedia.org/wiki/Julie_Rosewald",
    },
    {
        "id": 6,
        "name": 'Marie "Selika" Williams',
        "maidenName": "Smith",
        "voiceType": "coloratura soprano",
        "yearsActiveStart": "1870s",
        "yearsActiveEnd": "1911",
        "dateOfDeath": "1937-05-19",
        "url": "https://en.wikipedia.org/wiki/Marie_Selika_Williams",
    },
    {
        "id": 7,
        "name": "Ada Adini",
        "maidenName": "Schillinger",
        "voiceType": "soprano",
        "yearsActiveStart": "1876",
        "yearsActiveEnd": None,
        "dateOfDeath": "1924-02-22",
        "url": "https://en.wikipedia.org/wiki/Ada_Adini",
    },
    {
        "id": 8,
        "name": "Selma Kronold",
        "maidenName": None,
        "voiceType": "soprano",
        "yearsActiveStart": "1877",
        "yearsActiveEnd": "1904",
        "dateOfDeath": "1920-10-09",
        "url": "https://en.wikipedia.org/wiki/Selma_Kronold",
    },
    {
        "id": 9,
        "name": "Jessie Fremont Bartlett",
        "maidenName": None,
        "voiceType": "contralto",
        "yearsActiveStart": "1879",
        "yearsActiveEnd": None,
        "dateOfDeath": "1905-05-14",
        "url": "https://en.wikipedia.org/wiki/Jessie_Bartlett_Davis",
    },
    {
        "id": 10,
        "name": 'Emma "Nevada"',
        "maidenName": "Wixom",
        "voiceType": "coloratura soprano",
        "yearsActiveStart": "1880",
        "yearsActiveEnd": "1910",
        "dateOfDeath": "1940-06-20",
        "url": "https://en.wikipedia.org/wiki/Selma_Kronold",
    },
    {
        "id": 11,
        "name": "Matilda Sissieretta Jones",
        "maidenName": "Joyner",
        "voiceType": "soprano",
        "yearsActiveStart": "1887",
        "yearsActiveEnd": "1899",
        "dateOfDeath": "1933-06-24",
        "url": "https://en.wikipedia.org/wiki/Sissieretta_Jones",
    },
    {
        "id": 12,
        "name": "Kate Condon",
        "maidenName": None,
        "voiceType": "contralto",
        "yearsActiveStart": "1900",
        "yearsActiveEnd": None,
        "dateOfDeath": "1941-05-27",
        "url": "https://en.wikipedia.org/wiki/Kate_Condon",
    },
]
